export const storeData = [
  {
    id: 1,
    storeName: "Chop Asap",
    logo: "path_to_logo.jpg",
    email: "app@chopasap.com",
    number: "672765292",
    city: "Yaounde",
    address: "Yaounde Cameroon",
    country: "Cameroon",
    balance: "2300 cfa",
    status: "Verified"
  },
  {
    id: 2,
    storeName: "Correct Chop",
    logo: "path_to_logo.jpg",
    email: "app@chopasap.com",
    number: "672765292",
    city: "Yaounde",
    address: "Yaounde Cameroon",
    country: "Cameroon",
    balance: "2300 cfa",
    status: "Verified"
  },
  {
    id: 3,
    storeName: "Chop Corner",
    logo: "path_to_logo.jpg",
    email: "contact@chopcorner.com",
    number: "675324567",
    city: "Douala",
    address: "Douala Cameroon",
    country: "Cameroon",
    balance: "1800 cfa",
    status: "Verified"
  },
  {
    id: 4,
    storeName: "Mama Cuisine",
    logo: "path_to_logo.jpg",
    email: "mama@cuisine.com",
    number: "699876543",
    city: "Buea",
    address: "Molyko, Buea",
    country: "Cameroon",
    balance: "3200 cfa",
    status: "Verified"
  },
  {
    id: 5,
    storeName: "Tasty Bites",
    logo: "path_to_logo.jpg",
    email: "tasty@bites.com",
    number: "670123456",
    city: "Bamenda",
    address: "Commercial Ave, Bamenda",
    country: "Cameroon",
    balance: "2100 cfa",
    status: "Verified"
  },
  {
    id: 6,
    storeName: "Delish Hub",
    logo: "path_to_logo.jpg",
    email: "hello@delishhub.com",
    number: "673456789",
    city: "Limbe",
    address: "Church Street, Limbe",
    country: "Cameroon",
    balance: "2500 cfa",
    status: "Verified"
  },
  {
    id: 7,
    storeName: "Fast Feast",
    logo: "path_to_logo.jpg",
    email: "fast@feast.com",
    number: "678765432",
    city: "Yaounde",
    address: "Ekounou, Yaounde",
    country: "Cameroon",
    balance: "2700 cfa",
    status: "Verified"
  },
  {
    id: 8,
    storeName: "Kitchen Express",
    logo: "path_to_logo.jpg",
    email: "express@kitchen.com",
    number: "670987654",
    city: "Douala",
    address: "Bonaberi, Douala",
    country: "Cameroon",
    balance: "3000 cfa",
    status: "Verified"
  },
  {
    id: 9,
    storeName: "Hotpot Delight",
    logo: "path_to_logo.jpg",
    email: "info@hotpotdelight.com",
    number: "671234567",
    city: "Bafoussam",
    address: "Bamendzi, Bafoussam",
    country: "Cameroon",
    balance: "1900 cfa",
    status: "Verified"
  },
  {
    id: 10,
    storeName: "Savory Stop",
    logo: "path_to_logo.jpg",
    email: "support@savorystop.com",
    number: "679123456",
    city: "Kribi",
    address: "Beach Road, Kribi",
    country: "Cameroon",
    balance: "2800 cfa",
    status: "Verified"
  },
  {
    id: 11,
    storeName: "Local Eats",
    logo: "path_to_logo.jpg",
    email: "hello@localeats.com",
    number: "674321098",
    city: "Yaounde",
    address: "Mendong, Yaounde",
    country: "Cameroon",
    balance: "3100 cfa",
    status: "Verified"
  },
  {
    id: 12,
    storeName: "Bon Appetit",
    logo: "path_to_logo.jpg",
    email: "admin@bonappetit.com",
    number: "679987654",
    city: "Douala",
    address: "Akwa, Douala",
    country: "Cameroon",
    balance: "2600 cfa",
    status: "Verified"
  },
  {
    id: 13,
    storeName: "Urban Chop",
    logo: "path_to_logo.jpg",
    email: "urban@chop.com",
    number: "671111222",
    city: "Buea",
    address: "Sandpit, Buea",
    country: "Cameroon",
    balance: "2200 cfa",
    status: "Verified"
  },
  {
    id: 14,
    storeName: "Grill House",
    logo: "path_to_logo.jpg",
    email: "grill@house.com",
    number: "678000999",
    city: "Bamenda",
    address: "Old Town, Bamenda",
    country: "Cameroon",
    balance: "2400 cfa",
    status: "Verified"
  },
  {
    id: 15,
    storeName: "Chop Nation",
    logo: "path_to_logo.jpg",
    email: "nation@chop.com",
    number: "673333444",
    city: "Yaounde",
    address: "Ngousso, Yaounde",
    country: "Cameroon",
    balance: "2300 cfa",
    status: "Verified"
  },
  {
    id: 16,
    storeName: "City Snacks",
    logo: "path_to_logo.jpg",
    email: "city@snacks.com",
    number: "679456789",
    city: "Douala",
    address: "Makepe, Douala",
    country: "Cameroon",
    balance: "2900 cfa",
    status: "Verified"
  },
  {
    id: 17,
    storeName: "Royal Meals",
    logo: "path_to_logo.jpg",
    email: "royal@meals.com",
    number: "674000123",
    city: "Buea",
    address: "Great Soppo, Buea",
    country: "Cameroon",
    balance: "2000 cfa",
    status: "Verified"
  },
  {
    id: 18,
    storeName: "Flavor Point",
    logo: "path_to_logo.jpg",
    email: "flavor@point.com",
    number: "672999888",
    city: "Bamenda",
    address: "Mankon, Bamenda",
    country: "Cameroon",
    balance: "2450 cfa",
    status: "Verified"
  },
  {
    id: 19,
    storeName: "Food Lounge",
    logo: "path_to_logo.jpg",
    email: "info@foodlounge.com",
    number: "673666555",
    city: "Yaounde",
    address: "Nkolbisson, Yaounde",
    country: "Cameroon",
    balance: "2750 cfa",
    status: "Verified"
  },
  {
    id: 20,
    storeName: "Gourmet Spot",
    logo: "path_to_logo.jpg",
    email: "gourmet@spot.com",
    number: "675111222",
    city: "Limbe",
    address: "Mile 1, Limbe",
    country: "Cameroon",
    balance: "2550 cfa",
    status: "Verified"
  }
];


export const orders = [
  {
    orderId: "ORD001",
    product: "Laptop",
    price: 1200,
    userName: "John Doe",
    number: "1234567890",
    email: "johndoe@example.com",
    orderType: "Online",
    status: "Shipped",
  },
  {
    orderId: "ORD002",
    product: "Smartphone",
    price: 800,
    userName: "Jane Smith",
    number: "9876543210",
    email: "janesmith@example.com",
    orderType: "In-store",
    status: "Pending",
  },
  {
    orderId: "ORD003",
    product: "Headphones",
    price: 150,
    userName: "Alice Johnson",
    number: "4567891230",
    email: "alicej@example.com",
    orderType: "Online",
    status: "Delivered",
  },
  {
    orderId: "ORD004",
    product: "Smartwatch",
    price: 200,
    userName: "Bob Williams",
    number: "3216549870",
    email: "bobw@example.com",
    orderType: "Online",
    status: "Processing",
  },
  {
    orderId: "ORD005",
    product: "Tablet",
    price: 500,
    userName: "Emma Brown",
    number: "6549873210",
    email: "emmab@example.com",
    orderType: "In-store",
    status: "Shipped",
  },
  {
    orderId: "ORD006",
    product: "Gaming Console",
    price: 400,
    userName: "Chris Evans",
    number: "7893216540",
    email: "chris@example.com",
    orderType: "Online",
    status: "Cancelled",
  },
  {
    orderId: "ORD007",
    product: "Camera",
    price: 700,
    userName: "Olivia Green",
    number: "9638527410",
    email: "oliviag@example.com",
    orderType: "Online",
    status: "Pending",
  },
  {
    orderId: "ORD008",
    product: "Wireless Earbuds",
    price: 120,
    userName: "Daniel Lee",
    number: "8529637410",
    email: "daniel@example.com",
    orderType: "In-store",
    status: "Delivered",
  },
  {
    orderId: "ORD009",
    product: "External Hard Drive",
    price: 100,
    userName: "Sophia Martin",
    number: "7418529630",
    email: "sophiam@example.com",
    orderType: "Online",
    status: "Processing",
  },
  {
    orderId: "ORD010",
    product: "Bluetooth Speaker",
    price: 90,
    userName: "Michael Carter",
    number: "3692581470",
    email: "michael@example.com",
    orderType: "Online",
    status: "Shipped",
  },
  {
    orderId: "ORD011",
    product: "Keyboard",
    price: 60,
    userName: "Emily Turner",
    number: "1593578520",
    email: "emily@example.com",
    orderType: "In-store",
    status: "Cancelled",
  },
  {
    orderId: "ORD012",
    product: "Monitor",
    price: 300,
    userName: "Liam Anderson",
    number: "2581473690",
    email: "liama@example.com",
    orderType: "Online",
    status: "Delivered",
  },
  {
    orderId: "ORD013",
    product: "Mouse",
    price: 40,
    userName: "Charlotte Walker",
    number: "3571598520",
    email: "charlotte@example.com",
    orderType: "Online",
    status: "Processing",
  },
  {
    orderId: "ORD014",
    product: "Router",
    price: 80,
    userName: "Benjamin Hall",
    number: "1237894560",
    email: "benjamin@example.com",
    orderType: "In-store",
    status: "Shipped",
  },
  {
    orderId: "ORD015",
    product: "SSD 1TB",
    price: 150,
    userName: "Isabella Adams",
    number: "4561237890",
    email: "isabella@example.com",
    orderType: "Online",
    status: "Pending",
  },
  {
    orderId: "ORD016",
    product: "Graphics Card",
    price: 900,
    userName: "James Wright",
    number: "7896543210",
    email: "james@example.com",
    orderType: "Online",
    status: "Delivered",
  },
  {
    orderId: "ORD017",
    product: "VR Headset",
    price: 600,
    userName: "Amelia Scott",
    number: "9632587410",
    email: "amelia@example.com",
    orderType: "In-store",
    status: "Processing",
  },
  {
    orderId: "ORD018",
    product: "Portable Charger",
    price: 50,
    userName: "Elijah Harris",
    number: "7419638520",
    email: "elijah@example.com",
    orderType: "Online",
    status: "Cancelled",
  },
  {
    orderId: "ORD019",
    product: "Microphone",
    price: 180,
    userName: "Mia Nelson",
    number: "8527419630",
    email: "mia@example.com",
    orderType: "Online",
    status: "Shipped",
  },
  {
    orderId: "ORD020",
    product: "Drone",
    price: 1100,
    userName: "Alexander Baker",
    number: "3698521470",
    email: "alexander@example.com",
    orderType: "In-store",
    status: "Delivered",
  },
];


